apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-python2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-python2
  template:
    metadata:
      labels:
        app: flask-app-python2
    spec:
      containers:
      - name: flask-app-python2
        image: registry.example.com/flask-app-python2:$BUILD_NUMBER
        ports:
        - containerPort: 5000
